site:
  about:
    siteName: 'Think. Do. Learn.'
    subtitle: 'Reading isn''t free. The cost is opening your mind to a new perspective.'
    siteDescription: 'Reading isn''t free. The cost is opening your mind to a new perspective.'
    avatar: '/assets/media/logo.jpg'

theme:
  social:
#    facebook: 'facebookUsername'
    twitter: 'danialgoodwin'
#    instagram: 'instagramHandle'
    github: 'danialgoodwin'
    other:
      - label: 'example'
        link: 'https://www.example.com'
        icon: 'fa-tag'
  menu:
    - type: 'page'
      title: 'Home'
      url: '/'
    - type: "wikiSections"
    - type: 'taxonomy'
      taxonomyType: 'categories'
      includeTerms: true
      termsAtRoot: true
    - type: 'page'
      title: 'About'
      itemId: 'Danial Goodwin'
    - type: "pages"
      atRoot: true
  sidebar:
    - type: recentPosts
      limit: 3
      category: gallery
      noWrapper: true
      template:
        - 'includes/postPreview_mini'
    - type: recentPosts
      limit: 5
      category: personal
      noWrapper: true
      template:
        - 'includes/postPreview_list'
  extraCss:
    - 'assets/css/extraCss.scss'
    - 'assets/css/pygments.scss'
  extraJs:
    - 'assets/js/extraJs.js'

services:
  generators:
    externalIndices:
      - 'https://orchid.netlify.com/meta/all.index.json'
